#!/usr/bin/env python3
"""
HTML Test Report Generator for contentstack-model-generator.

Converts a .trx test-results file (and an optional Cobertura coverage.xml)
into a single self-contained HTML report: pass/fail summary, per-class test
breakdown with failure details, and a code coverage section.

Usage:
  python3 Scripts/generate_test_report.py <path-to-trx> [path-to-coverage.cobertura.xml]

Or run tests first to generate both inputs:
  dotnet test contentstack.model.generator.tests/contentstack.model.generator.tests.csproj \\
      --logger "trx;LogFileName=test-results.trx" \\
      --collect:"XPlat Code Coverage" \\
      --results-directory contentstack.model.generator.tests/TestResults

Uses only the Python standard library (xml.etree.ElementTree) - no extra
dependencies to install. The .trx/coverage files parsed here are always
locally generated by `dotnet test`, not untrusted input.
"""

import glob
import os
import sys
import xml.etree.ElementTree as ET
from datetime import datetime

TRX_NS = {'': 'http://microsoft.com/schemas/VisualStudio/TeamTest/2010'}


def escape_html(text):
    if text is None:
        return ""
    text = str(text)
    return (text
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
            .replace('"', '&quot;')
            .replace("'", '&#39;'))


class TestReportGenerator:
    def __init__(self, trx_file, coverage_file=None):
        self.trx_file = trx_file
        self.coverage_file = coverage_file
        self.results = {
            'total': 0,
            'passed': 0,
            'failed': 0,
            'skipped': 0,
            'tests': [],
        }
        self.coverage = None

    def parse_trx(self):
        tree = ET.parse(self.trx_file)
        root = tree.getroot()

        result_summary = root.find('.//ResultSummary', TRX_NS)
        counters = result_summary.find('Counters', TRX_NS) if result_summary is not None else None
        if counters is not None:
            self.results['total'] = int(counters.get('total', 0))
            self.results['passed'] = int(counters.get('passed', 0))
            self.results['failed'] = int(counters.get('failed', 0))
            self.results['skipped'] = int(counters.get('notExecuted', 0))

        unit_tests_by_id = {el.get('id'): el for el in root.findall('.//UnitTest', TRX_NS)}

        for test_result in root.findall('.//UnitTestResult', TRX_NS):
            test_name = test_result.get('testName', 'Unknown')
            outcome = test_result.get('outcome', 'Unknown')
            duration = test_result.get('duration', '0')

            try:
                hours, minutes, seconds = duration.split(':')
                total_seconds = int(hours) * 3600 + int(minutes) * 60 + float(seconds)
                duration_str = f"{total_seconds:.3f}s"
            except (ValueError, AttributeError):
                duration_str = duration

            error_message = None
            error_stacktrace = None
            output_elem = test_result.find('Output', TRX_NS)
            if output_elem is not None:
                error_info = output_elem.find('ErrorInfo', TRX_NS)
                if error_info is not None:
                    message_elem = error_info.find('Message', TRX_NS)
                    stacktrace_elem = error_info.find('StackTrace', TRX_NS)
                    if message_elem is not None:
                        error_message = message_elem.text
                    if stacktrace_elem is not None:
                        error_stacktrace = stacktrace_elem.text

            test_def = unit_tests_by_id.get(test_result.get('testId', ''))
            category = 'General'
            if test_def is not None:
                test_method = test_def.find('.//TestMethod', TRX_NS)
                if test_method is not None:
                    class_name = test_method.get('className', '')
                    if class_name:
                        category = class_name.split('.')[-1]

            self.results['tests'].append({
                'name': test_name,
                'outcome': outcome,
                'duration': duration_str,
                'category': category,
                'error_message': error_message,
                'error_stacktrace': error_stacktrace,
            })

        return True

    def parse_coverage(self):
        if not self.coverage_file or not os.path.exists(self.coverage_file):
            return

        tree = ET.parse(self.coverage_file)
        root = tree.getroot()

        # ModelGenerator.cs (and any other file) is split across multiple
        # <class> entries by coverlet (the class itself plus one per
        # compiler-generated async state machine) - aggregate by filename
        # so each source file shows as a single row.
        files = {}
        for cls in root.iter('class'):
            filename = cls.get('filename', cls.get('name', 'unknown'))
            lines_el = cls.find('lines')
            if lines_el is None:
                continue
            entry = files.setdefault(filename, {'valid': 0, 'covered': 0})
            for line in lines_el.findall('line'):
                entry['valid'] += 1
                if int(line.get('hits', 0)) > 0:
                    entry['covered'] += 1

        classes = []
        total_valid = 0
        total_covered = 0
        for filename, stats in files.items():
            valid = stats['valid']
            covered = stats['covered']
            total_valid += valid
            total_covered += covered
            classes.append({
                'filename': filename,
                'lines_valid': valid,
                'lines_covered': covered,
                'line_rate': (covered / valid * 100) if valid else 0.0,
            })

        classes.sort(key=lambda c: c['line_rate'])

        self.coverage = {
            'line_rate': float(root.get('line-rate', 0)) * 100,
            'branch_rate': float(root.get('branch-rate', 0)) * 100,
            'lines_valid': total_valid,
            'lines_covered': total_covered,
            'classes': classes,
        }

    def generate_coverage_section_html(self):
        if not self.coverage:
            return ""

        cov = self.coverage
        rows_html = ""
        for c in cov['classes']:
            rate = c['line_rate']
            bar_class = 'good' if rate >= 80 else 'warn' if rate >= 50 else 'bad'
            rows_html += f"""
                        <tr>
                            <td class="coverage-filename">{escape_html(c['filename'])}</td>
                            <td>
                                <div class="coverage-bar-track">
                                    <div class="coverage-bar-fill {bar_class}" style="width: {rate}%"></div>
                                </div>
                            </td>
                            <td class="coverage-pct">{rate:.1f}%</td>
                            <td class="coverage-counts">{c['lines_covered']} / {c['lines_valid']}</td>
                        </tr>
"""

        return f"""
        <div class="coverage-section">
            <h2 style="margin-bottom: 30px; font-size: 2em;">Code Coverage</h2>
            <div class="summary">
                <div class="summary-card">
                    <div class="number total">{cov['line_rate']:.1f}%</div>
                    <div class="label">Line Coverage</div>
                </div>
                <div class="summary-card">
                    <div class="number total">{cov['branch_rate']:.1f}%</div>
                    <div class="label">Branch Coverage</div>
                </div>
                <div class="summary-card">
                    <div class="number passed">{cov['lines_covered']}</div>
                    <div class="label">Lines Covered</div>
                </div>
                <div class="summary-card">
                    <div class="number">{cov['lines_valid']}</div>
                    <div class="label">Total Lines</div>
                </div>
            </div>
            <table class="test-table coverage-table">
                <thead>
                    <tr>
                        <th style="width: 40%">File</th>
                        <th style="width: 30%">Line Coverage</th>
                        <th style="width: 10%">%</th>
                        <th style="width: 20%">Lines</th>
                    </tr>
                </thead>
                <tbody>
{rows_html}
                </tbody>
            </table>
        </div>
"""

    def generate_html(self, output_file):
        pass_rate = (self.results['passed'] / self.results['total'] * 100) if self.results['total'] > 0 else 0

        tests_by_category = {}
        for test in self.results['tests']:
            tests_by_category.setdefault(test['category'], []).append(test)
        sorted_categories = sorted(tests_by_category.keys())

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>contentstack-model-generator - Test Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
            color: #333;
        }}

        .container {{
            max-width: 1600px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }}

        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }}

        .header h1 {{ font-size: 2.5em; margin-bottom: 10px; font-weight: 700; }}
        .header p {{ font-size: 1.1em; opacity: 0.9; }}

        .summary {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            padding: 40px;
            background: #f8f9fa;
        }}

        .summary-card {{
            background: white;
            padding: 25px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            text-align: center;
            transition: transform 0.2s;
        }}

        .summary-card:hover {{ transform: translateY(-5px); box-shadow: 0 4px 12px rgba(0,0,0,0.15); }}
        .summary-card .number {{ font-size: 3em; font-weight: bold; margin-bottom: 10px; }}
        .summary-card .label {{ font-size: 0.9em; color: #666; text-transform: uppercase; letter-spacing: 1px; }}

        .passed {{ color: #28a745; }}
        .failed {{ color: #dc3545; }}
        .skipped {{ color: #ffc107; }}
        .total {{ color: #007bff; }}

        .pass-rate {{ padding: 30px 40px; background: white; text-align: center; border-top: 3px solid #f8f9fa; }}

        .pass-rate-bar {{
            width: 100%;
            height: 40px;
            background: #e9ecef;
            border-radius: 20px;
            overflow: hidden;
            margin: 20px 0;
        }}

        .pass-rate-fill {{
            height: 100%;
            background: linear-gradient(90deg, #28a745 0%, #20c997 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-weight: bold;
            font-size: 1.1em;
        }}

        .coverage-section {{ padding: 40px; background: #f8f9fa; border-top: 3px solid #e9ecef; }}

        .coverage-bar-track {{
            width: 100%;
            height: 18px;
            background: #e9ecef;
            border-radius: 10px;
            overflow: hidden;
        }}

        .coverage-bar-fill {{ height: 100%; border-radius: 10px; }}
        .coverage-bar-fill.good {{ background: linear-gradient(90deg, #28a745, #20c997); }}
        .coverage-bar-fill.warn {{ background: linear-gradient(90deg, #ffc107, #fd7e14); }}
        .coverage-bar-fill.bad {{ background: linear-gradient(90deg, #dc3545, #c82333); }}

        .coverage-filename {{ font-family: 'Consolas', 'Monaco', monospace; font-size: 0.9em; }}
        .coverage-pct {{ font-weight: 600; }}
        .coverage-counts {{ color: #666; font-size: 0.9em; }}

        .test-results {{ padding: 40px; }}
        .category {{ margin-bottom: 30px; }}

        .category-header {{
            background: #f8f9fa;
            padding: 15px 20px;
            border-left: 4px solid #667eea;
            margin-bottom: 15px;
            border-radius: 4px;
            cursor: pointer;
            display: flex;
            justify-content: space-between;
            align-items: center;
            transition: background 0.2s;
        }}

        .category-header:hover {{ background: #e9ecef; }}
        .category-title {{ font-size: 1.3em; font-weight: 600; color: #333; }}
        .category-stats {{ font-size: 0.9em; color: #666; }}

        .test-table {{
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}

        .test-table thead {{ background: #667eea; color: white; }}
        .test-table th {{ padding: 15px; text-align: left; font-weight: 600; text-transform: uppercase; font-size: 0.85em; letter-spacing: 0.5px; }}
        .test-table td {{ padding: 15px; border-bottom: 1px solid #e9ecef; }}
        .test-table tr:last-child td {{ border-bottom: none; }}
        .test-table tbody tr:hover {{ background: #f8f9fa; }}

        .test-name {{ font-family: 'Consolas', 'Monaco', monospace; font-size: 0.9em; cursor: pointer; color: #007bff; }}
        .test-name:hover {{ text-decoration: underline; }}

        .status-badge {{ display: inline-block; padding: 6px 12px; border-radius: 20px; font-size: 0.85em; font-weight: 600; text-transform: uppercase; }}
        .status-passed {{ background: #d4edda; color: #155724; }}
        .status-failed {{ background: #f8d7da; color: #721c24; }}
        .status-skipped {{ background: #fff3cd; color: #856404; }}

        .test-details-container {{
            background: #f8f9fa;
            border-left: 4px solid #dc3545;
            margin-top: 15px;
            padding: 20px;
            border-radius: 4px;
            display: none;
        }}

        .test-details-container.show {{ display: block; }}

        .error-message {{ font-family: 'Consolas', 'Monaco', monospace; font-size: 0.9em; color: #721c24; white-space: pre-wrap; margin-bottom: 10px; }}
        .error-stacktrace {{
            font-family: 'Consolas', 'Monaco', monospace;
            font-size: 0.8em;
            color: #666;
            white-space: pre-wrap;
            background: white;
            padding: 10px;
            border-radius: 4px;
            max-height: 300px;
            overflow-y: auto;
        }}

        .footer {{ background: #f8f9fa; padding: 30px; text-align: center; color: #666; border-top: 3px solid #e9ecef; }}
        .footer p {{ margin: 5px 0; }}

        .collapsible {{ display: none; }}
        .collapsible.active {{ display: block; }}
        .toggle-icon {{ transition: transform 0.3s; }}
        .toggle-icon.rotated {{ transform: rotate(90deg); }}

        @media print {{
            body {{ background: white; padding: 0; }}
            .container {{ box-shadow: none; }}
            .collapsible {{ display: block !important; }}
            .test-details-container {{ display: block !important; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>contentstack-model-generator Test Report</h1>
            <p>{datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
        </div>

        <div class="summary">
            <div class="summary-card">
                <div class="number total">{self.results['total']}</div>
                <div class="label">Total Tests</div>
            </div>
            <div class="summary-card">
                <div class="number passed">{self.results['passed']}</div>
                <div class="label">Passed</div>
            </div>
            <div class="summary-card">
                <div class="number failed">{self.results['failed']}</div>
                <div class="label">Failed</div>
            </div>
            <div class="summary-card">
                <div class="number skipped">{self.results['skipped']}</div>
                <div class="label">Skipped</div>
            </div>
        </div>

        <div class="pass-rate">
            <h2>Pass Rate</h2>
            <div class="pass-rate-bar">
                <div class="pass-rate-fill" style="width: {pass_rate}%">{pass_rate:.1f}%</div>
            </div>
        </div>
{self.generate_coverage_section_html()}
        <div class="test-results">
            <h2 style="margin-bottom: 30px; font-size: 2em;">Test Results by Class</h2>
"""

        for category in sorted_categories:
            tests = tests_by_category[category]
            passed = sum(1 for t in tests if t['outcome'] == 'Passed')
            failed = sum(1 for t in tests if t['outcome'] == 'Failed')
            skipped = sum(1 for t in tests if t['outcome'] == 'NotExecuted')

            html += f"""
            <div class="category">
                <div class="category-header" onclick="toggleCategory('{category}')">
                    <div>
                        <span class="toggle-icon" id="icon-{category}">&#9654;</span>
                        <span class="category-title">{escape_html(category)}</span>
                    </div>
                    <div class="category-stats">
                        <span class="passed">{passed} passed</span> &middot;
                        <span class="failed">{failed} failed</span> &middot;
                        <span class="skipped">{skipped} skipped</span> &middot;
                        <span>{len(tests)} total</span>
                    </div>
                </div>
                <div id="{category}" class="collapsible">
                    <table class="test-table">
                        <thead>
                            <tr>
                                <th style="width: 60%">Test Name</th>
                                <th style="width: 20%">Status</th>
                                <th style="width: 20%">Duration</th>
                            </tr>
                        </thead>
                        <tbody>
"""

            for test_idx, test in enumerate(tests):
                status_class = ('status-passed' if test['outcome'] == 'Passed'
                                 else 'status-failed' if test['outcome'] == 'Failed'
                                 else 'status-skipped')
                test_id = f"test-{category}-{test_idx}"

                html += f"""
                            <tr>
                                <td>
                                    <div class="test-name" onclick="toggleTestDetails('{test_id}')">{escape_html(test['name'])}</div>
"""
                if test['outcome'] == 'Failed' and (test['error_message'] or test['error_stacktrace']):
                    html += f"""
                                    <div id="{test_id}" class="test-details-container">
                                        <div class="error-message"><strong>Error:</strong><br>{escape_html(test['error_message'])}</div>
"""
                    if test['error_stacktrace']:
                        html += f"""
                                        <details>
                                            <summary style="cursor: pointer; font-weight: bold; margin-bottom: 10px;">Stack Trace</summary>
                                            <div class="error-stacktrace">{escape_html(test['error_stacktrace'])}</div>
                                        </details>
"""
                    html += """
                                    </div>
"""

                html += f"""
                                </td>
                                <td><span class="status-badge {status_class}">{test['outcome']}</span></td>
                                <td>{test['duration']}</td>
                            </tr>
"""

            html += """
                        </tbody>
                    </table>
                </div>
            </div>
"""

        html += f"""
        </div>

        <div class="footer">
            <p><strong>contentstack-model-generator Test Report</strong></p>
            <p>Generated on {datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}</p>
        </div>
    </div>

    <script>
        function toggleCategory(categoryId) {{
            const element = document.getElementById(categoryId);
            const icon = document.getElementById('icon-' + categoryId);
            element.classList.toggle('active');
            icon.classList.toggle('rotated');
        }}

        function toggleTestDetails(testId) {{
            const element = document.getElementById(testId);
            if (element) {{ element.classList.toggle('show'); }}
        }}

        document.addEventListener('DOMContentLoaded', function() {{
            document.querySelectorAll('.category').forEach(category => {{
                const stats = category.querySelector('.category-stats');
                if (stats && !stats.textContent.includes('0 failed')) {{
                    toggleCategory(category.querySelector('.collapsible').id);
                }}
            }});
        }});
    </script>
</body>
</html>
"""

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(html)

        print(f"Test report generated: {output_file}")
        return output_file


def find_first(pattern):
    matches = glob.glob(pattern, recursive=True)
    return matches[0] if matches else None


def main():
    print("=" * 80)
    print("contentstack-model-generator Test Report Generator")
    print("=" * 80)

    trx_file = sys.argv[1] if len(sys.argv) > 1 else find_first('contentstack.model.generator.tests/TestResults/**/*.trx')
    coverage_file = sys.argv[2] if len(sys.argv) > 2 else find_first('contentstack.model.generator.tests/TestResults/**/coverage.cobertura.xml')

    if not trx_file or not os.path.exists(trx_file):
        print("\nError: No .trx file found!")
        print(__doc__)
        sys.exit(1)

    print(f"\nTRX file: {trx_file}")
    print(f"Coverage file: {coverage_file or '(none found - report will omit coverage section)'}")

    generator = TestReportGenerator(trx_file, coverage_file)

    print("\nParsing test results...")
    generator.parse_trx()
    print(f"Found {generator.results['total']} tests "
          f"({generator.results['passed']} passed, {generator.results['failed']} failed, "
          f"{generator.results['skipped']} skipped)")

    if coverage_file:
        print("\nParsing coverage data...")
        generator.parse_coverage()
        if generator.coverage:
            print(f"Line coverage: {generator.coverage['line_rate']:.1f}% "
                  f"({generator.coverage['lines_covered']}/{generator.coverage['lines_valid']} lines)")

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_file = generator.generate_html(f'test-report_{timestamp}.html')

    print("\n" + "=" * 80)
    print(f"Done. Open: file://{os.path.abspath(output_file)}")
    print("=" * 80)


if __name__ == "__main__":
    main()
